### ISSUE TITLE
Question about using locks

### ISSUE THREAD

**Issue by ManuelZ** [debbynirwan/mapping_controller#1]
Hi, this is a nice and educative project, thanks for sharing!

I'd like to know why are you using `threading.Lock()` in your callbacks?

**Comment by debbynirwan** [comment]
> Hi, this is a nice and educative project, thanks for sharing!
> 
> I'd like to know why are you using `threading.Lock()` in your callbacks?

I thought the sensor callback and the timer callback both can try to update at the same time hence the lock.
